
spring:
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:5005
  cloud:
    config:
      enabled: true
      name: user
      profile: dev
      label: master

server:
  port: ${PORT:5001}
