
spring:
  application:
    name: USER-SERVICE
  config:
    import: configserver:https://api-cloud-config.herokuapp.com
  cloud:
    config:
      enabled: true
      name: user
      profile: dev
      label: master

server:
  port: ${PORT:5001}
